### ISSUE TITLE
Create documentation how to use tcp protocol

### ISSUE THREAD

**Issue by myroslavlisniak** [scalecube/gatling-tcp-extensions#3]

**Comment by ajres** [comment]
I just found your tcp extension, do you have even basic instructions on how to record and playback tcp requests against an endpoint?

**Comment by myroslavlisniak** [comment]
Hi, for now I have no documentation, but can you explain more what is needed and I'll try to add it if it supported.

**Comment by myroslavlisniak** [comment]
Closed, check readme
